## 001_pytorch.ipynb

In [2]:
import torch
print(torch.__version__)

1.9.0+cpu


In [3]:
my_data = [
    [1, 2],
    [3, 4]
]

In [5]:
type(my_data)

list

In [6]:
torch.tensor(my_data), torch.tensor(my_data).dtype

(tensor([[1, 2],
         [3, 4]]),
 torch.int64)

In [7]:
my_tensor = torch.tensor(my_data)
my_tensor.dtype

torch.int64

In [8]:
type(my_tensor), my_tensor.type()

(torch.Tensor, 'torch.LongTensor')

In [10]:
my_tensor.device
# my_tensor.to("cuda")  tensor를 GPU에서 사용하도록 처리

device(type='cpu')

In [11]:
my_tensor.to("cuda")

AssertionError: Torch not compiled with CUDA enabled

In [12]:
torch.zeros((2, 2))

tensor([[0., 0.],
        [0., 0.]])

In [13]:
torch.ones((2, 2))

tensor([[1., 1.],
        [1., 1.]])

In [14]:
new_tensor = torch.ones((2, 2))
type(new_tensor), new_tensor.type()

(torch.Tensor, 'torch.FloatTensor')

In [16]:
new_tensor.dtype

torch.float32

In [19]:
my_data

[[1, 2], [3, 4]]

In [20]:
updated_new_tensor = new_tensor.new_tensor(my_data)

In [21]:
new_tensor

tensor([[1., 1.],
        [1., 1.]])

In [22]:
updated_new_tensor

tensor([[1., 2.],
        [3., 4.]])

## 왜 new_tensor로 tensor의 내용을 바꿔야 하나? 
## tensor라는 것은 cpu나 gpu 메모리에 상주하고 있는 데이터, 이 때 properties을 유지하고 싶은 때가 있다.
## 특정 메모리에 지정되어 있는 tensor를 그대로 사용하면서, 즉, 주소를 유지하면서 tensor의 내용을 바꿀 때!
## value만 바뀌지, 그 tensor의 property들은 유지가 된다.

In [23]:
updated_new_tensor.dtype

torch.float32

In [33]:
another_tensor = torch.zeros((2, 2), dtype= torch.int8)
another_tensor.dtype

torch.int8

In [34]:
new_data = [
    [1, 2],
    [3, 4],
    [5, 6]
]

In [35]:
another_tensor.new_tensor(new_data)

tensor([[1, 2],
        [3, 4],
        [5, 6]], dtype=torch.int8)

In [36]:
another_tensor.dtype

torch.int8

In [37]:
shape = (2, 3)
my_tensor = torch.rand(shape) # 이 때 값들은 0 ~ 1 사이의 값

In [39]:
my_tensor, my_tensor.dtype

(tensor([[0.2595, 0.5876, 0.9710],
         [0.6288, 0.7684, 0.8865]]),
 torch.float32)

In [48]:
x_rand = torch.rand_like(my_tensor, dtype=torch.float64)
x_rand, x_rand.dtype

(tensor([[0.4446, 0.7282, 0.1392],
         [0.7401, 0.2007, 0.6631]], dtype=torch.float64),
 torch.float64)